In [199]:
import pandas as pd
import numpy as np

In [200]:
# create a DataFrame from a numpy array
array = np.array([[2,3,4],[3,5,4]])
df = pd.DataFrame(array)

In [201]:
# create a DataFrame from a python list
mylist = [[2,3,5,6],[2,3,4,5]]
df2 = pd.DataFrame(mylist)
df2

   0  1  2  3
0  2  3  5  6
1  2  3  4  5

In [202]:
# create a DataFrame from a python dictionnary, must precise index if working with scalar values
mydic = {1:'manger',2:'boire',3:'dormir','dormir':'bien'}
df3 = pd.DataFrame(mydic,index=[0])
df3

        1      2       3 dormir
0  manger  boire  dormir   bien

In [203]:
#save df3 into a csv
df3.to_csv('df3.csv')

In [204]:
df = pd.read_csv('iris-data-clean.csv')
df.head(3)
df.tail()
df.shape
#get info on columns with nb of non-null values and types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
sepal_length_cm    149 non-null float64
sepal_width_cm     149 non-null float64
petal_length_cm    149 non-null float64
petal_width_cm     149 non-null float64
class              149 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [205]:
#to describe numerical variables
df.describe()

       sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
count       149.000000      149.000000       149.000000      149.000000
mean          5.847651        3.059732         3.775168        1.209732
std           0.799542        0.430104         1.758720        0.762191
min           4.400000        2.000000         1.000000        0.100000
25%           5.100000        2.800000         1.600000        0.300000
50%           5.800000        3.000000         4.400000        1.300000
75%           6.400000        3.300000         5.100000        1.800000
max           7.900000        4.400000         6.900000        2.500000

In [206]:
#print number of each distinct values, and names of unique columns
print(df['sepal_length_cm'].value_counts(dropna=False))
df.columns.unique()

5.0    10
6.3     9
5.1     9
5.7     9
6.7     8
5.5     7
5.6     7
5.8     7
6.4     7
6.0     6
4.9     6
5.4     6
6.1     6
6.5     5
4.8     5
6.9     4
5.2     4
6.2     4
4.6     4
6.8     3
7.2     3
5.9     3
4.4     3
7.7     3
6.6     2
4.7     2
7.1     1
7.6     1
7.4     1
7.9     1
5.3     1
7.0     1
7.3     1
Name: sepal_length_cm, dtype: int64

Index(['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm',
       'petal_width_cm', 'class'],
      dtype='object')

In [207]:
#mean of each column, each function can be applied to one column only
df.mean()

sepal_length_cm    5.847651
sepal_width_cm     3.059732
petal_length_cm    3.775168
petal_width_cm     1.209732
dtype: float64

In [208]:
#correlation matrix
df.corr()

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm
sepal_length_cm,1.000000,-0.125633,0.848414,0.803132
sepal_width_cm,-0.125633,1.000000,-0.443664,-0.378865
petal_length_cm,0.848414,-0.443664,1.000000,0.960885
petal_width_cm,0.803132,-0.378865,0.960885,1.000000

In [209]:
#number on non-null values of each columns
df.count()

sepal_length_cm    149
sepal_width_cm     149
petal_length_cm    149
petal_width_cm     149
class              149
dtype: int64

In [210]:
#min and max of each columns
df.max()
df.min()

sepal_length_cm            4.4
sepal_width_cm               2
petal_length_cm              1
petal_width_cm             0.1
class              Iris-setosa
dtype: object

In [211]:
#median of each columns
df.median()

sepal_length_cm    5.8
sepal_width_cm     3.0
petal_length_cm    4.4
petal_width_cm     1.3
dtype: float64

In [212]:
#variance of each columns
df.var()

sepal_length_cm    0.639268
sepal_width_cm     0.184989
petal_length_cm    3.093095
petal_width_cm     0.580935
dtype: float64

In [213]:
#standard deviation of each columns
df.std()

sepal_length_cm    0.799542
sepal_width_cm     0.430104
petal_length_cm    1.758720
petal_width_cm     0.762191
dtype: float64

In [214]:
#selection
df['petal_width_cm']
df[['petal_width_cm','class']]
df.iloc[0][3]
df.iloc[2]
df.loc[1]

sepal_length_cm            4.9
sepal_width_cm               3
petal_length_cm            1.4
petal_width_cm             0.2
class              Iris-setosa
Name: 1, dtype: object

In [215]:
#boolean filtering
df[df['petal_length_cm']<=1.2]

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class
13,5.7,3.0,1.1,0.1,Iris-setosa
14,5.8,4.0,1.2,0.2,Iris-setosa
22,4.6,3.6,1.0,0.2,Iris-setosa
35,5.0,3.2,1.2,0.2,Iris-setosa

In [216]:
#boolean filtering 2
df[(df['petal_length_cm']<=1.2) & ((df['sepal_length_cm']>5.0) | (df['petal_length_cm']==1))]

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class
13,5.7,3.0,1.1,0.1,Iris-setosa
14,5.8,4.0,1.2,0.2,Iris-setosa
22,4.6,3.6,1.0,0.2,Iris-setosa

In [198]:
#sorting
df.sort_values('sepal_width_cm')
#in decending order
df.sort_values('sepal_width_cm',ascending=False)

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class
15,5.7,4.4,1.5,0.40,Iris-setosa
33,5.5,4.2,1.4,0.20,Iris-setosa
32,5.2,4.1,1.5,0.10,Iris-setosa
14,5.8,4.0,1.2,0.20,Iris-setosa
16,5.4,3.9,1.3,0.40,Iris-setosa
5,5.4,3.9,1.7,0.40,Iris-setosa
19,5.1,3.8,1.5,0.30,Iris-setosa
43,5.1,3.8,1.9,0.40,Iris-setosa
45,5.1,3.8,1.6,0.20,Iris-setosa
130,7.9,3.8,6.4,2.00,Iris-virginica
116,7.7,3.8,6.7,2.20,Iris-virginica
18,5.7,3.8,1.7,0.30,Iris-setosa
47,5.3,3.7,1.5,0.20,Iris-setosa
10,5.4,3.7,1.5,0.25,Iris-setosa
21,5.1,3.7,1.5,0.40,Iris-setosa
4,5.0,3.6,1.4,0.20,Iris-setosa
22,4.6,3.6,1.0,0.20,Iris-setosa
108,7.2,3.6,6.1,2.50,Iris-virginica
36,5.5,3.5,1.3,0.20,Iris-setosa
0,5.1,3.5,1.4,0.20,Iris-setosa
17,5.1,3.5,1.4,0.30,Iris-setosa
40,5.0,3.5,1.3,0.30,Iris-setosa
42,5.0,3.5,1.6,0.60,Iris-setosa
27,5.2,3.5,1.5,0.20,Iris-setosa
39,5.1,3.4,1.5,0.20,Iris-setosa
28,5.2,3.4,1.4,0.20,Iris-setosa
135,6.3,3.4,5.6,2.40,Iris-virginica
31,5.4,3.4,1.5,0.40,Iris-setosa
84,6.0,3.4,4.5,1.60,Iris-versicolor
20,5.4,3.4,1.7,0.20,Iris-setosa
...,...,...,...,...,...
93,5.6,2.7,4.2,1.30,Iris-versicolor
58,5.2,2.7,3.9,1.40,Iris-versicolor
100,5.8,2.7,5.1,1.90,Iris-virginica
66,5.8,2.7,4.1,1.00,Iris-versicolor
110,6.4,2.7,5.3,1.90,Iris-virginica
81,5.8,2.7,3.9,1.20,Iris-versicolor
122,6.3,2.7,4.9,1.80,Iris-virginica
117,7.7,2.6,6.9,2.30,Iris-virginica
89,5.5,2.6,4.4,1.20,Iris-versicolor
78,5.7,2.6,3.5,1.00,Iris-versicolor
91,5.8,2.6,4.0,1.20,Iris-versicolor
133,6.1,2.6,5.6,1.40,Iris-virginica
71,6.3,2.5,4.9,1.50,Iris-versicolor
145,6.3,2.5,5.0,2.30,Iris-virginica
88,5.5,2.5,4.0,1.30,Iris-versicolor
68,5.6,2.5,3.9,1.10,Iris-versicolor
97,5.1,2.5,3.0,1.10,Iris-versicolor
112,5.7,2.5,5.0,2.00,Iris-virginica
105,4.9,2.5,4.5,1.70,Iris-virginica
107,6.7,2.5,5.8,1.80,Iris-virginica
79,5.5,2.4,3.8,1.10,Iris-versicolor
80,5.5,2.4,3.7,1.00,Iris-versicolor
56,4.9,2.4,3.3,1.00,Iris-versicolor
92,5.0,2.3,3.3,1.00,Iris-versicolor
52,5.5,2.3,4.0,1.30,Iris-versicolor
86,6.3,2.3,4.4,1.30,Iris-versicolor
118,6.0,2.2,5.0,1.50,Iris-virginica
67,6.2,2.2,4.5,1.50,Iris-versicolor
61,6.0,2.2,4.0,1.00,Iris-versicolor
59,5.0,2.0,3.5,1.00,Iris-versicolor

In [223]:
# null values for each column
df.isnull().sum()

sepal_length_cm    0
sepal_width_cm     0
petal_length_cm    0
petal_width_cm     0
class              0
dtype: int64

In [224]:
#drop rows with null values
df.dropna()
#drop columns
df.dropna(axis=1)
#fill with mean
df['petal_width_cm'].fillna(df['petal_width_cm'].mean())

0      0.20
1      0.20
2      0.20
3      0.20
4      0.20
5      0.40
6      0.30
7      0.25
8      0.25
9      0.25
10     0.25
11     0.25
12     0.10
13     0.10
14     0.20
15     0.40
16     0.40
17     0.30
18     0.30
19     0.30
20     0.20
21     0.40
22     0.20
23     0.50
24     0.20
25     0.20
26     0.40
27     0.20
28     0.20
29     0.20
       ...
119    2.30
120    2.00
121    2.00
122    1.80
123    2.10
124    1.80
125    1.80
126    1.80
127    2.10
128    1.60
129    1.90
130    2.00
131    2.20
132    1.50
133    1.40
134    2.30
135    2.40
136    1.80
137    1.80
138    2.10
139    2.40
140    2.30
141    1.90
142    2.30
143    2.50
144    2.30
145    2.30
146    2.00
147    2.30
148    1.80
Name: petal_width_cm, Length: 149, dtype: float64

In [226]:
#to replace several values with specific content
df['petal_width_cm'].replace([0.2,0.3],['manger','boire'])

0      manger
1      manger
2      manger
3      manger
4      manger
5         0.4
6       boire
7        0.25
8        0.25
9        0.25
10       0.25
11       0.25
12        0.1
13        0.1
14     manger
15        0.4
16        0.4
17      boire
18      boire
19      boire
20     manger
21        0.4
22     manger
23        0.5
24     manger
25     manger
26        0.4
27     manger
28     manger
29     manger
        ...
119       2.3
120         2
121         2
122       1.8
123       2.1
124       1.8
125       1.8
126       1.8
127       2.1
128       1.6
129       1.9
130         2
131       2.2
132       1.5
133       1.4
134       2.3
135       2.4
136       1.8
137       1.8
138       2.1
139       2.4
140       2.3
141       1.9
142       2.3
143       2.5
144       2.3
145       2.3
146         2
147       2.3
148       1.8
Name: petal_width_cm, Length: 149, dtype: object

In [227]:
#rename a column
df.rename(columns = {'petal_width_cm' : 'petal_width'})

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width,class
0,5.1,3.5,1.4,0.20,Iris-setosa
1,4.9,3.0,1.4,0.20,Iris-setosa
2,4.7,3.2,1.3,0.20,Iris-setosa
3,4.6,3.1,1.5,0.20,Iris-setosa
4,5.0,3.6,1.4,0.20,Iris-setosa
5,5.4,3.9,1.7,0.40,Iris-setosa
6,4.6,3.4,1.4,0.30,Iris-setosa
7,5.0,3.4,1.5,0.25,Iris-setosa
8,4.4,2.9,1.4,0.25,Iris-setosa
9,4.9,3.1,1.5,0.25,Iris-setosa
10,5.4,3.7,1.5,0.25,Iris-setosa
11,4.8,3.4,1.6,0.25,Iris-setosa
12,4.8,3.0,1.4,0.10,Iris-setosa
13,5.7,3.0,1.1,0.10,Iris-setosa
14,5.8,4.0,1.2,0.20,Iris-setosa
15,5.7,4.4,1.5,0.40,Iris-setosa
16,5.4,3.9,1.3,0.40,Iris-setosa
17,5.1,3.5,1.4,0.30,Iris-setosa
18,5.7,3.8,1.7,0.30,Iris-setosa
19,5.1,3.8,1.5,0.30,Iris-setosa
20,5.4,3.4,1.7,0.20,Iris-setosa
21,5.1,3.7,1.5,0.40,Iris-setosa
22,4.6,3.6,1.0,0.20,Iris-setosa
23,5.1,3.3,1.7,0.50,Iris-setosa
24,4.8,3.4,1.9,0.20,Iris-setosa
25,5.0,3.0,1.6,0.20,Iris-setosa
26,5.0,3.4,1.6,0.40,Iris-setosa
27,5.2,3.5,1.5,0.20,Iris-setosa
28,5.2,3.4,1.4,0.20,Iris-setosa
29,4.7,3.2,1.6,0.20,Iris-setosa
...,...,...,...,...,...
119,6.9,3.2,5.7,2.30,Iris-virginica
120,5.6,2.8,4.9,2.00,Iris-virginica
121,5.6,2.8,6.7,2.00,Iris-virginica
122,6.3,2.7,4.9,1.80,Iris-virginica
123,6.7,3.3,5.7,2.10,Iris-virginica
124,7.2,3.2,6.0,1.80,Iris-virginica
125,6.2,2.8,4.8,1.80,Iris-virginica
126,6.1,3.0,4.9,1.80,Iris-virginica
127,6.4,2.8,5.6,2.10,Iris-virginica
128,7.2,3.0,5.8,1.60,Iris-virginica
129,7.4,2.8,6.1,1.90,Iris-virginica
130,7.9,3.8,6.4,2.00,Iris-virginica
131,6.4,2.8,5.6,2.20,Iris-virginica
132,6.3,2.8,5.1,1.50,Iris-virginica
133,6.1,2.6,5.6,1.40,Iris-virginica
134,7.7,3.0,6.1,2.30,Iris-virginica
135,6.3,3.4,5.6,2.40,Iris-virginica
136,6.4,3.1,5.5,1.80,Iris-virginica
137,6.0,3.0,4.8,1.80,Iris-virginica
138,6.9,3.1,5.4,2.10,Iris-virginica
139,6.7,3.1,5.6,2.40,Iris-virginica
140,6.9,3.1,5.1,2.30,Iris-virginica
141,5.8,2.7,5.1,1.90,Iris-virginica
142,6.8,3.2,5.9,2.30,Iris-virginica
143,6.7,3.3,5.7,2.50,Iris-virginica
144,6.7,3.0,5.2,2.30,Iris-virginica
145,6.3,2.5,5.0,2.30,Iris-virginica
146,6.5,3.0,5.2,2.00,Iris-virginica
147,6.2,3.4,5.4,2.30,Iris-virginica
148,5.9,3.0,5.1,1.80,Iris-virginica

In [234]:
#to add df1 at the end of df2
df1.append(df2)
#to add columns of df1 after df2
df.concat([df1,df2],axis=1)

NameError: name 'df1' is not defined